name:   Production Release

on:
    workflow_dispatch:
        inputs:
            milestone:
                description: 'The milestone to generate a release for'
                required:   true
                type:   string
